apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-hello
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-web-hello
  template:
    metadata:
      labels:
        app: k8s-web-hello
    spec:
      containers:
        - name: k8s-web-hello
          image: victornovik/k8s-web-hello-ru:3.0.0
          resources:
            requests:
              memory: "64M"
              cpu: "250m" # 1\4 of CPU core
            limits:
              memory: "128M" # 128 Megabytes (Ei, Pi, Ti, Gi, Mi - mebibytes, Ki)
              cpu: "500m" # 1\2 of CPU core
          ports:
            - containerPort: 3000
          readinessProbe:
              httpGet:
                path: /health
                port: 3000
              initialDelaySeconds: 1
              periodSeconds: 2
          livenessProbe:
              httpGet:
                path: /health
                port: 3000
              initialDelaySeconds: 1
              periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-web-hello
spec:
  type: LoadBalancer
  selector:
    app: k8s-web-hello
  ports:
    - port: 3333
      targetPort: 3000